# -*- coding: utf-8 -*-

class Base(object):
    
    def retorna_base_intencoes(self):
            return [('abra meu facebook','abrir_facebook'),        
                    ('abrir facebook','abrir_facebook'),
                    ('abrir página do facebook','abrir_facebook'),
                    ('rodar facebook','abrir_facebook'),
                    ('executar facebook','abrir_facebook'),
                    ('facebook','abrir_facebook'),
                    ('abra meu face','abrir_facebook'),
                    ('abrir face','abrir_facebook'),
                    ('face','abrir_facebook'),

                    ('ligar lampada', 'ligar_lampada_quarto'),
                    ('ligar a lampada', 'ligar_lampada_quarto'),
                    ('acender lampada', 'ligar_lampada_quarto'),
                    ('acender a lampada', 'ligar_lampada_quarto'),
                    ('ligar a lampada', 'ligar_lampada_quarto'),
                    ('acender a luz', 'ligar_lampada_quarto'),
                    ('acende a luz', 'ligar_lampada_quarto'),
                    ('acender luz', 'ligar_lampada_quarto'),
                    ('lampada ligar', 'ligar_lampada_quarto'),

                    ('desligar lampada', 'desligar_lampada_quarto'),
                    ('desligar a lampada', 'desligar_lampada_quarto'),
                    ('desliga a lampada', 'desligar_lampada_quarto'),
                    ('apagar lampada', 'desligar_lampada_quarto'),
                    ('apagar a lampada', 'desligar_lampada_quarto'),
                    ('apagar luz', 'desligar_lampada_quarto'),
                    ('apagar a luz', 'desligar_lampada_quarto'),
                    ('apaga a luz', 'desligar_lampada_quarto'),

                    ('abra meu youtube','abrir_youtube'),
                    ('abra meu youtube', 'abrir_youtube'),
                    ('abrir youtube','abrir_youtube'),
                    ('abrir página do youtube','abrir_youtube'),
                    ('rodar youtube','abrir_youtube'),
                    ('executar youtube','abrir_youtube'),
                    ('youtube','abrir_youtube'),

                    ('buscar o sinonimo de','buscar_sinonimo'),
                    ('sinonimo de ','buscar_sinonimo'),
                    ('quero saber o sinonimo de ','buscar_sinonimo'),
                    ('qual o sinonimo de','buscar_sinonimo'),
                    ('qual o sinonimo da palavra','buscar_sinonimo'),
                    ('sinonimo da palavra','buscar_sinonimo'),

                    ('buscar o antonimo de','buscar_antonimo'),
                    ('antonimo de ','buscar_antonimo'),
                    ('quero saber o antonimo de ','buscar_antonimo'),
                    ('qual o antonimo de','buscar_antonimo'),
                    ('qual o antonimo da palavra','buscar_antonimo'),
                    ('antonimo da palavra','buscar_antonimo'),

                    ('buscar o significado de','buscar_significado'),
                    ('significado de ','buscar_significado'),
                    ('quero saber o significado de ','buscar_significado'),
                    ('qual o significado de','buscar_significado'),
                    ('qual o significado da palavra','buscar_significado'),
                    ('significado da palavra','buscar_significado'),


                    ('quantas horas são','hora_atual'),
                    ('que horas são','hora_atual'),
                    ('horas','hora_atual'),
                    ('que hora é agora','hora_atual'),
                    ('horário atual','hora_atual'),
                    ('horas por favor','hora_atual'),
                    ('horas e minutos','hora_atual'),
                    ('horas','hora_atual'),
                    ('minutos','hora_atual'),

                    ('aumentar volume','aumentar_volume'),
                    ('aumentar som','aumentar_volume'),
                    ('aumentar volume do som','aumentar_volume'),
                    ('aumentar audio','aumentar_volume'),
                    ('aumentar audio volume','aumentar_volume'),
                    ('subir volume','aumentar_volume'),
                    ('elevar o  som','aumentar_volume'),
                    ('elevar volume do som','aumentar_volume'),
                    ('subir audio','aumentar_volume'),
                    ('elevar audio volume','aumentar_volume'),

                    ('diminuir volume','diminuir_volume'),
                    ('diminuir som','diminuir_volume'),
                    ('diminuir volume do som','diminuir_volume'),
                    ('diminuir audio','diminuir_volume'),
                    ('diminuir audio volume','diminuir_volume'),
                    ('descer volume','diminuir_volume'),
                    ('abaixar som','diminuir_volume'),
                    ('abaixar volume do som','diminuir_volume'),
                    ('abaixar audio','diminuir_volume'),
                    ('abaixar audio volume','diminuir_volume'),

                    ('tocar musica','tocar_musica'),
                    ('tocar uma musica', 'tocar_musica'),
                    ('tocar ouvir musica', 'tocar_musica'),
                    ('reproduzir uma musica', 'tocar_musica'),
                    ('tocar musicas','tocar_musica'),
                    ('quero escutar musicas','tocar_musica'),
                    ('escutar musicas','tocar_musica'),

                    ('pesquise por','buscar_no_google'),
                    ('pesquise no google','buscar_no_google'),
                    ('pesquisar por','buscar_no_google'),
                    ('pesquise sobre','buscar_no_google'),
                    ('pesquise na internet','buscar_no_google'),
                    ('pesquise na internet sobre','buscar_no_google'),
                    ('busque','buscar_no_google'),
                    ('busque no google','buscar_no_google'),
                    ('busque na internet','buscar_no_google'),
                    ('busque','buscar_no_google'),
                    ('pesquise por','buscar_no_google'),
                    ('buscar','buscar_no_google'),
                    ('pesquisar','buscar_no_google'),

                    ('Conte-me uma piada', 'contar_piada'),
                    ('Quero ouvir uma piada', 'contar_piada'),
                    ('Conta uma piada', 'contar_piada'),
                    ('Conta uma história', 'contar_piada'),
                    ('Conte algo engracado', 'contar_piada'),
                    ('Diga algo engraçado', 'contar_piada'),
                    ('Me conta uma piada', 'contar_piada'),
                    ('Conte-me uma piada', 'contar_piada')]
        

if __name__ == '__main__':    
    print("Base de dados de INTENÇÕES - Apenas para import!")